name: key_path
description: A starting point for Dart libraries or applications.
version: 0.0.1

environment:
  sdk: ^3.6.0

dependencies:
  macros: 0.1.3-main.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
