name: composable_architecture
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/viniciusaro/dart-composable-architecture

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  async: ^2.12.0
  equatable: ^2.0.7

dev_dependencies:
  fake_async: 1.3.2 
  lints: ^5.0.0
  test: ^1.24.0