name: composable_architecture
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/viniciusaro/dart-composable-architecture
publish_to: none

environment:
  sdk: ^3.6.0

dependencies:
  analyzer: ^7.2.0
  async: ^2.12.0
  build: ^2.4.2
  freezed_annotation: ^3.0.0
  source_gen: ^2.0.0

dev_dependencies:
  build_runner: ^2.4.15
  fake_async: 1.3.2 
  freezed: 3.0.3
  lints: ^5.0.0
  test: ^1.24.0